### PR TITLE
Fix for #216

### PR DESCRIPTION
**Pull request by simo-11**
Fix replaces use of current working directory by using directory of test file to allow running tests anywhere.
This pull request does not handle packaging issue that leaves data files off.

### CODE REVIEW

**Review by Czarified — COMMENTED** [review]
Nice small fix. We definitely should avoid using cwd where possible. My two cents:

`pathlib` is already imported in the module, and the calls to get the `__file__` directory would be very similar to the `dirname()`.

I believe pathlib is also a more modern standard library module, and generally more preferred. The typical usage is to grab the Path object directly, though, not what we currently have. `from pathlib import Path`

**Comment by robbievanleeuwen** [comment]
@simo-11 thanks for the fix, wondering if the recent two commits are related to this PR?

@Czarified thanks for the input! I'm definitely not up to date with what is more modern. @simo-11 would you be happy to try the fix using ``pathlib``?

**Comment by simo-11** [comment]
Using pathlib is fine. I have just knew dirname and knew it could handle this.

**Comment by robbievanleeuwen** [comment]
@simo-11 thanks. I'm happy to make changes to PR myself but have noticed you have included an example file ``rectangle.py`` in this branch, is there an intention to add this to the library as well?

**Comment by simo-11** [comment]
rectangle.py is my own experiment. I'm not offering currently to be included in main.

**Comment by robbievanleeuwen** [comment]
@simo-11 ok that's fine, are you happy for me to remove ``rectangle.py`` from the master branch in [simo-11/section-properties](https://github.com/simo-11/section-properties)? If not,  I can create a new PR with the changes.

**Comment by simo-11** [comment]
I'm ok with with any solution. Sorry for non clean pull request.

**Pull request merged**
