### PR TITLE
[ImportDXF] - First attempt - NOT TO MERGE

### PR DESCRIPTION
**Pull request by MZecchetto**
Here we go @robbievanleeuwen.
This PR add a `ImportDXF` class to `section.py` starting from the code posted by @Vinythewheel in https://github.com/robbievanleeuwen/section-properties/issues/10.
Few notes:

- holes, if any, must be defined as POINT in a layer called "holes";

- control_points are all the POINTs contained in the layer called "control_points". As it is, it is mandatory. However, we can load all the points defined in the dxf file except the ones in "holes", increasing the flexibility. To be agreed.

- I accidentally removed the `shift` option. Should I add it again? Is it required?

- POLYLINEs entities are not supported. Should we? To be agreed.

@Agent6-6-6 , @Vinythewheel your feedback is appreciated as well.

Kind regards,

Massimiliano

To do:

- [ ] add tests

- [ ] add documentation

- [ ] reach consensus about control_points

- [ ] reach consensus about POLYLINEs

- [ ] reach consensus about shift

### CODE REVIEW

**Comment by MZecchetto** [comment]
any comment?
@Vinythewheel does it work for you?

**Comment by Vinythewheel** [comment]
Damn, really sorry, I’m so busy these days. I use SectionProp on a daily basis. But I made so mush modification to the code, I can’t just swap with the new code without spending hours to make it work with my integration.
You will have to let me mush more time to bench the new code. Like 2-3 months, when my actual crazy contract will end.




[cid:image002.png@01D6A911.E8501970]

Vincent Leroux Ing.
2711 Lyall, Montréal, Qc, H1N 3G8
(514)794-2010
vleroux@genilec.com<mailto:vleroux@genilec.com>
www.genilec.com<http://genilec.com/>

**Comment by robbievanleeuwen** [comment]
Hi @MZecchetto,

Apologies for the lack of response, I was recently in an accident and have had a bit of a slow recovery. I will try to have a look at this in the coming days :)

Robbie

**Comment by MZecchetto** [comment]
@robbievanleeuwen, @Vinythewheel,
no problem at all. Take your time to review and provide feedback.
Stay healthy, kind regards.

Massimiliano

**Comment by robbievanleeuwen** [comment]
Hi @MZecchetto,

Finally getting around to having a look at this. Do you have any example dxf files that I can use to help test the code?

Cheers,
Robbie

**Comment by MZecchetto** [comment]
@robbievanleeuwen,
please find hereafter a couple of tests I did. Results of these two are provided in https://github.com/robbievanleeuwen/section-properties/issues/10.
Let me know if you need other examples.
Cheers,

Massimiliano 

[test_circle_00.zip](https://github.com/robbievanleeuwen/section-properties/files/5723002/test_circle_00.zip)

[Section-Rail8po_MZ_1.zip](https://github.com/robbievanleeuwen/section-properties/files/5722993/Section-Rail8po_MZ_1.zip)

**Comment by MZecchetto** [comment]
@robbievanleeuwen,
now this branch is working properly with _ezdxf_.

**Comment by robbievanleeuwen** [comment]
Hi @MZecchetto,

As the pre-processor is being overhauled to use shapely (#42), we have taken a different approach utilising shapely for the dxf import function. If you are interested in helping out on this you can jump over to that pull request.

Again sorry for the delayed response on this one and thanks for the code :smile:

Robbie

**Pull request closed without merging**
