### PR TITLE
v3.0

### PR DESCRIPTION
**Pull request by robbievanleeuwen**
# ``sectionproperties`` v3.0

## :boom: Breaking Changes

- Update section property ``get()`` methods behaviour as per #272. The behaviour is unchanged for analyses without material properties, however composite analyses now require material specific get methods to be used.
  - e.g. for a composite analysis, ``get_ic()`` will raise an error telling the user to instead use ``get_eic()``.
- Stress plotting methods have been simplified to improve maintainability and code repetition.
  - Stress plots are now generated by calling the ``StressPost.plot_stress()`` method, with a string determining the type of stress to plot. The previous implementation had a separate method for each different type of stress plot which was very repetitive.
  - There is a similar implementation for generate vector stress plots.
- ``get_stress_at_point()`` method removed, user can use more versatile ``get_stress_at_points()`` method instead.
- Pythonic renaming of methods and variables, e.g. ``get_As()`` becomes ``get_as()`` for retrieving shear areas, moments and shears change from ``Mxx`` and ``Vx`` to ``mxx`` and ``vx``.
- Concrete section library:
  - Added option for variable covers to top, bottom and side reinforcement.
  - Renamed argument names to be more pythonic.
  - Reinforcement now requires an area and diameter (area used to determine discretised circle geometry, diameter used to calculate cover and location).

## :rocket: Features

- Packaging and dependency management with poetry.
- Improve length/readability of imports by placing key classes in ``__init__.py`` files.
  - e.g. ``from sectionproperties.pre.library.primitive_sections import rectangular_section`` becomes ``from sectionproperties.pre.library import rectangular_section`` and ``from sectionproperties.analysis.section import Section`` becomes ``from sectionproperties.analysis import Section`` (note not a breaking feature as previous imports still work).
- #259
- #274 

## :bug: Fixes

- #255
- #268
- #272 

## :rotating_light: Testing

- Use nox & nox-poetry for testing.
- Move ``test_plastic_centroid()`` to ``test_plastic.py``.
- Further TBC.

## :construction_worker: Continuous Integration

- Added dependabot.
- Added labeller and release drafter automation.
- Added pre-commit checks.
- Updated all workflows.

## :books: Documentation

- Changed documentation theme to [furo](https://github.com/pradyunsg/furo).
- General overhaul of the documentation.
- Auto-generate API documentation using sphinx autodoc.
- Auto-generate images in documentation using matplotlib plot directive.
- Change examples from sphinx gallery to notebook style with nbsphinx.
- Add intersphinx mappings.

## :lipstick: Style

- Fully implement typing.
- Added flake8 linter to pre-commit.
- Added darglint docstring linter to pre-commit.
- Added isort to pre-commit.
- Added pyupgrade to pre-commit.
- General refactor to improve readability and maintainability, e.g. reduce amount of code in ``section.py``: ``PlasticSection`` -> ``plastic_section.py``, ``StressPost`` and ``StressResult`` -> ``stress_post.py``, ``SectionProperties`` -> ``post.py``.
- Generally changed type of a point from ``list[float]`` to a ``tuple[float, float]``.

## Other

- Restructured package by adding ``src`` folder.

### CODE REVIEW

**Comment by robbievanleeuwen** [comment]
@connorferster thanks for the offer for help - if you have time one thing that would be great would be having a look at #255.

**Comment by connorferster** [comment]
V3.0 looks awesome. Will do #255. Did the upstream issue with import_dxf only returning one single geometry from a DXF file that had many geometries get resolved? If not, can work on that too.

Is the triangle dependency still locking us into Python 3.9?

**Comment by ccaprani** [comment]
Looking good @robbievanleeuwen ! I'd like it if `rhino3dm` could be removed as a dependency & be optional. It's a relatively edge use-case I think, and a risk to long term sustainability...the benefits of 3.11 should be realised by what's mostly a native python application as soon as possible.

**Comment by robbievanleeuwen** [comment]
This is a good point @ccaprani! I'll have a play with around with the dependencies - I'll also have to figure out how to only run the rhino tests for certain versions of python, but I'm pretty sure this is possible with nox!

**Comment by Spectre5** [comment]
It is definitely possible with pytest itself and they examples of similar situations in the docs

**Comment by robbievanleeuwen** [comment]
Thanks @Spectre5, definitely a simpler solution - seems like the [skipif](https://docs.pytest.org/en/7.1.x/reference/reference.html?highlight=skipif#pytest.mark.skipif) marker can do this!

**Comment by ccaprani** [comment]
@robbievanleeuwen if I've understood correctly, can I suggest that cad2shapely and rhino3dm dependencies are seperately optional? I can see the temptation to join them, but I see them as separate use-cases. Preferable not to need rhino3dm just to do a DXF import imo. Even if currently both are limited to 3.10, this could change for one or other.

**Comment by robbievanleeuwen** [comment]
Hi @ccaprani , thanks for the feedback. Yes I agree, this is a good idea to separate the two!

I will create the following extras:

1. ``pip install sectionproperties[dxf]``
2. ``pip install sectionproperties[rhino]``

**Pull request merged**
