### PR TITLE
Fix legend formatting

### PR DESCRIPTION
**Pull request by Agent6-6-6**
@robbievanleeuwen, I believe this addresses #188 

I've only tested it briefly on a few examples where I previously had legend formatting issues since it was so intermittent

But I think the issue was calling `tight_layout()` after setting the aspect ratio for the plot did something weird for certain aspect ratio plots. Calling it beforehand seems to work as intended.

### CODE REVIEW

**Review by robbievanleeuwen — CHANGES_REQUESTED** [review]
Hi @Agent6-6-6 thanks for this, it's certainly an improvement on what's currently happening.

In some cases this cuts off the title of the plots, see some of the [examples](https://sectionproperties--235.org.readthedocs.build/en/235/sphinx_gallery_examples/index.html) in the gallery that are built from this pull request. I think overall this is still better than what is currently happening.

Could I get you to run ``black`` on the code so that its correctly formatted and I will merge.

Cheers!

**Comment by Agent6-6-6** [comment]
@robbievanleeuwen, are you just using the default line length in black (88 I think)?

Forgot I have it set to a slightly longer line length which reformatted a few longer lines, but will change and resubmit. 

Hadn't noticed the title getting cutoff, will have a further play around after merging and see if that can be figured out.

**Comment by Agent6-6-6** [comment]
@robbievanleeuwen, 5a336abe18074b8a217c82c08e318322229b27d6 seems to fix the title cutting off on the examples. Just needed the title created prior to `tight_layout()`.

Should be good to merge once the tests pass

**Comment by robbievanleeuwen** [comment]
Great, thanks @Agent6-6-6!

**Pull request merged**
