### PR TITLE
Reference-Based Testing Additions

### PR DESCRIPTION
**Pull request by Czarified**
This is a PR with my additions for testing against known reference texts. I left is as a draft originally, while I worked out the docs side of things. See my comments below.

All tests are checked with at least 0.1% accuracy to the truth values of the reference material.

Fixtures are used where possible (a design trend I did not notice in the rest of our test suite... maybe I'll fix that in a future PR). Test code was kept as simple as feasible (an improvement from my original PR in v1). And docstrings/comments were included abundantly.

### A couple of notes:

1. I use the `pre.library.nastran_sections` here, since they easily create the more simplified geometry that Peery uses in the book, and I'm more familiar with their definitions. This has the benefit of slightly improving code coverage of the entire suite, as well (~+2%).
2. Since we haven't yet implemented a method for stress recovery at an exact location, I have a hacked approach of pulling out stress at a particular node. I know that nodes will exist where I want to recover stress results, in these examples.
3. The exception to the above is the Symmetric Bending case, where I just pull the max resultant stress on the section, which may or may not be at the correct location. This could use improvement.
4. The reason I mention doc pages in addition to the tests, is to make it abundantly clear to any experienced engineer reviewing this package, that our numbers align very well with known examples. Having the tests in the suite proves this, but having a page in the documentation outlining the results and examples should instill confidence in new users from the beginning.

### CODE REVIEW

**Comment by robbievanleeuwen** [comment]
This is great @Czarified! I think the documentation addition is worthwhile as well. Also like the cleanliness of the fixtures.

Look forward to merging this one :)

**Comment by Czarified** [comment]
I can't figure out how to build the docs locally, so I can proofread... I know for v2 it was swapped so only the source was left in the repo here, but when I try the typical sphinx-build command, there's no files...

```
sphinx-build -b html docs/source docs/build/html
```

**Comment by Czarified** [comment]
It makes sense to have these as part of the example gallery, so the code is executed live, each time. I think the testing docs page will just discuss this approach generally, and I'll try to add examples for all validation tests.

I still don't know how to build the docs locally, but I found a VSCode plugin that will let me preview individual pages. So I'll slowly work on it.

**Comment by robbievanleeuwen** [comment]
Hi @Czarified I'll have a look into the build issues tonight. Are you on windows?

**Comment by Czarified** [comment]
Yeah, I'm on Windows. It appears to build, just not sure what happens after
that...

**Comment by robbievanleeuwen** [comment]
Hi @Czarified, running ``sphinx-build -b html docs/source docs/build/html`` on my PC seems to work for me. Is there anything strange looking in the terminal output?

**Comment by robbievanleeuwen** [comment]
Long shot - my files don't show up in my IDE because they are hidden in the ``.gitignore``, but I can find them in windows explorer, is this maybe the issue?

**Comment by Czarified** [comment]
So i tried this on a different machine and I'm still lost.

In my terminal, with my venv active, I navigate to the section-properties root dir (the one that has docs, and examples folders). In here I run the command `sphinx-build -b html docs/source docs/build/html`.

I get this output in my terminal:
```
Running Sphinx v4.5.0
loading translations [en]... done
making output directory... done
generating gallery...
Using Sphinx-Gallery to convert rst text blocks to markdown for .ipynb files.
generating gallery for sphinx_gallery_examples\00-basic... [100%] 09_cad_import.pyon.py
```

When I navigate to the build folder (docs/build/html) in windows explorer, I don't see anything. The folder is there, but it's empty.

What am I missing??

**Comment by robbievanleeuwen** [comment]
This is very puzzling! Perhaps you are having an issue building the example ``09_cad_import.py``, as I get a bit more output in my terminal when building on windows:

```shell
➜ sphinx-build -b html docs/source docs/build/html
Running Sphinx v4.5.0
loading translations [en]... done
making output directory... done
generating gallery...
Using Sphinx-Gallery to convert rst text blocks to markdown for .ipynb files.
generating gallery for sphinx_gallery_examples\00-basic... [100%] 09_cad_import.pyon.py
generating gallery for sphinx_gallery_examples\01-advanced... [100%] 03_torsion_constant.pyy
computation time summary:
    - ..\..\examples\01-advanced\02_mesh_refinement.py:     29.80 sec   0.0 MB
    - ..\..\examples\00-basic\07_composite.py:              17.19 sec   0.0 MB
    - ..\..\examples\00-basic\06_stress.py:                 11.38 sec   0.0 MB
    - ..\..\examples\01-advanced\03_torsion_constant.py:     9.59 sec   0.0 MB
    - ..\..\examples\00-basic\08_frame.py:                   9.49 sec   0.0 MB
    - ..\..\examples\00-basic\04_merged.py:                  9.27 sec   0.0 MB
    - ..\..\examples\00-basic\09_cad_import.py:              8.36 sec   0.0 MB
    - ..\..\examples\00-basic\05_mirr_rot.py:                7.27 sec   0.0 MB
    - ..\..\examples\01-advanced\01_advanced_plotting.py:    6.86 sec   0.0 MB
    - ..\..\examples\00-basic\01_simple.py:                  4.26 sec   0.0 MB
    - ..\..\examples\00-basic\03_custom.py:                  4.19 sec   0.0 MB
    - ..\..\examples\00-basic\02_nastran_section.py:         3.04 sec   0.0 MB
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 10 source files that are out of date
updating environment: [new config] 25 added, 0 changed, 0 removed
reading sources... [100%] sphinx_gallery_examples/index                        stg
C:\Users\Robbie\Documents\Programming\section-properties\sectionproperties\pre\library\concrete_sections.py:docstring of sectionproperties.pre.library.concrete_sections.concrete_rectangular_section:15: ERROR: Unexpected indentation.
C:\Users\Robbie\Documents\Programming\section-properties\sectionproperties\pre\library\concrete_sections.py:docstring of sectionproperties.pre.library.concrete_sections.concrete_rectangular_section:15: ERROR: Unexpected indentation.
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] sphinx_gallery_examples/index                         tg
generating indices... genindex done
highlighting module code... [100%] sectionproperties.pre.rhino                 ions
writing additional pages... search done
copying images... [ 98%] sphinx_gallery_examples/01-advanced/images/thumb/sphx_glr_01_advanced_plotting_thumb.copying images... [ 99%] sphinx_gallery_examples/01-advanced/images/thumb/sphx_glr_02_mesh_refinement_thumb.pncopying images... [100%] sphinx_gallery_examples/01-advanced/images/thumb/sphx_glr_03_torsion_constant_thumb.png
copying downloadable files... [100%] ../sphinx_gallery_examples/01-advanced/03_torsion_constant.ipynbb
copying static files... done
copying extra files... done
dumping search index in English (code: en)... done
dumping object inventory... done
build succeeded, 2 warnings.

The HTML pages are in docs\build\html.

Sphinx-Gallery successfully executed 12 out of 12 files subselected by:

    gallery_conf["filename_pattern"] = '\\.py'
    gallery_conf["ignore_pattern"]   = '__init__\\.py'

after excluding 0 files that had previously been run (based on MD5).

embedding documentation hyperlinks...
embedding documentation hyperlinks for sphinx_gallery_examples... [100%] sg_execution_times.htmlll
```

I noticed that readthedocs is also having an issue building this example (e.g. second geometry [here](https://sectionproperties.readthedocs.io/en/latest/sphinx_gallery_examples/00-basic/09_cad_import.html#sphx-glr-sphinx-gallery-examples-00-basic-09-cad-import-py)) - this is something on the to-do list that I have to get to the bottom of eventually...

You could try ignoring that specific example in the docs build by adding this line to the ``sphinx_gallery_conf`` in ``conf.py``:

```python
"ignore_pattern": "09_cad_import.py",
```

Before trying to build I would delete the ``docs/build`` and the ``docs/source/sphinx_gallery_examples`` directories.

Fingers crossed this works!

**Comment by Czarified** [comment]
Looks like all I needed to do was delete the `docs/source/sphinx_gallery_examples` directory. I did get an error from sphinx this time, but it built! I can at least get back to work on my page now and we can see if the CI will build it.

**Comment by Czarified** [comment]
I added documentation, and examples. So the same code is copied a bit, but it will be executed by CI everytime the docs are built. So if the tests pass, it will pass CI, and it will build the examples showing proof to outsiders that it passed (in a more user-friendly way, I think).

I'm still wondering whether this should all _just_ be examples, or whether we want a separate docs page for testing, as i currently have. Would appreciate feedback on that.

**Comment by Czarified** [comment]
@robbievanleeuwen this is ready for review, but I will be unavailable to work any changes for a couple weeks.

**Comment by robbievanleeuwen** [comment]
Hi @Czarified thanks for your work on this! I've been pretty busy as of late, but looking forward to reviewing and merging :)

**Review by robbievanleeuwen — APPROVED** [review]
This looks great @Czarified! Merging in progress...

**Pull request merged**
