### PR TITLE
Geometry.align_center() -> Ability to align geometries to a point

### PR DESCRIPTION
**Pull request by connorferster**
* Added ability for `Geometry.align_center()` and `CompoundGeometry.align_center()` to accept an x, y coordinate as a valid input.
* Added tests for `Geometry.align_center()`

### CODE REVIEW

**Comment by connorferster** [comment]
As I was working on my sectionproperties lesson, I realized that I really wanted the ability to align geometries specific nodes on other geometries.

Don't know what's going on here, though:
image

**Comment by robbievanleeuwen** [comment]
Thanks for this @connorferster, will have a look at this tomorrow!

**Review by robbievanleeuwen — COMMENTED** [review]
Looks good @connorferster, I think we just need to add a bit more info in the ``align_center()`` docstrings to describe the new feature, i.e. the argument description in ``Geometry`` and the docstring description for both ``Geometry`` and ``CompoundGeometry``.

**Comment by robbievanleeuwen** [comment]
> Did something change with the GitHub actions script?

Fixed this, changed the package dependencies a bit and forgot the ``pytest`` module 🤦

**Comment by connorferster** [comment]
> Looks good @connorferster, I think we just need to add a bit more info in the `align_center()` docstrings to describe the new feature, i.e. the argument description in `Geometry` and the docstring description for both `Geometry` and `CompoundGeometry`.

Agreed! I missed some. Just added.

**Review by robbievanleeuwen — APPROVED** [review]

**Pull request merged**
