### PR TITLE
Moved imports for rhino libraries into rhino methods

### PR DESCRIPTION
**Pull request by connorferster**
Moved the rhino imports into rhino related methods so that they are only loaded when rhino import functionality are used.

### CODE REVIEW

**Review by robbievanleeuwen — COMMENTED** [review]
Looks good to me.

Not sure if you meant to add all those notebook files?

**Comment by connorferster** [comment]
Arrrgh!!! I did a git add -A and forgot that I cannot do that on this project.

Thanks for catching that…

**Comment by connorferster** [comment]
Fixes #191

**Comment by robbievanleeuwen** [comment]
Think there's still two additional files trying to make their way into this PR 😆

**Review by robbievanleeuwen — APPROVED** [review]

**Pull request merged**
