### PR TITLE
Fix: __sub__ method to prevent AttributeError when subtracting from CompoundGeometry

### LINKED ISSUE #194: __sub__ does not work for CompoundGeometry
The subtract operator `__sub__` does not appear to work as intended for `CompoundGeometry` objects.

I've been trying to modify the reinforced concrete library methods to generate geometry without any overlapping areas, see following example. Given the following methods:

```python
def concrete_rectangular_section(
    b: float,
    d: float,
    dia: float,
    n_bar: int,
    n_circle: int,
    cover: float,
    area: float = None,
    conc_mat: pre.Material = pre.DEFAULT_MATERIAL,
    steel_mat: pre.Material = pre.DEFAULT_MATERIAL,
) -> geometry.CompoundGeometry:
  
    if n_bar < 2:
        raise ValueError("Please provide 2 or more steel reinforcing bars.")

    geom = primitive_sections.rectangular_section(b=b, d=d, material=conc_mat)

    x_i = cover + dia / 2
    spacing = (b - 2 * cover - dia) / (n_bar - 1)

    for i in range(n_bar):
        if area:
            bar = primitive_sections.circular_section_by_area(
                area=area, n=n_circle, material=steel_mat
            )
        else:
            bar = primitive_sections.circular_section(
                d=dia, n=n_circle, material=steel_mat
            )

        bar = bar.shift_section(x_offset=x_i + spacing * i, y_offset=cover + dia / 2)

        geom = add_reinforcement(base_geom=geom, reinforcement=bar)

    return geom
```

```python
def add_reinforcement(
    base_geom: Union[geometry.Geometry, geometry.CompoundGeometry],
    reinforcement: geometry.Geometry,
):
    """Adds reinforcement geometry to a base concrete geometry object."""

    # make hole for reinforcement
    base_geom = base_geom - reinforcement

    # add reinforcement
    base_geom = base_geom + reinforcement

    # remove hole created in first operation
    base_geom.holes.pop()

    return base_geom
```

Running the following:

```python
from sectionproperties.pre.library.concrete_sections import concrete_rectangular_section
from sectionproperties.pre.pre import Material
from sectionproperties.analysis.section import Section

concrete = Material(
    name='Concrete', elastic_modulus=30.1e3, poissons_ratio=0.2, yield_strength=32,
    density=2.4e-6, color='lightgrey'
)
steel = Material(
    name='Steel', elastic_modulus=200e3, poissons_ratio=0.3, yield_strength=500,
    density=7.85e-6, color='grey'
)

geometry = concrete_rectangular_section(
    b=300, d=600, dia=20, n_bar=3, n_circle=24, cover=30, conc_mat=concrete, steel_mat=steel
)
geometry.create_mesh(mesh_sizes=[500])
geometry.plot_geometry()

sec = Section(geometry)
sec.plot_mesh()
```

Results in the following:

```shell
Traceback (most recent call last):
  File "/Users/robbievanleeuwen/Documents/Programming/section-properties/sectionproperties/pre/geometry.py", line 1051, in __sub__
    if self.assigned_control_point and new_polygon.contains(
AttributeError: 'CompoundGeometry' object has no attribute 'assigned_control_point'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 14, in <module>
    geometry = concrete_rectangular_section(
  File "/Users/robbievanleeuwen/Documents/Programming/section-properties/sectionproperties/pre/library/concrete_sections.py", line 93, in concrete_rectangular_section
    geom = add_reinforcement(base_geom=geom, reinforcement=bar)
  File "/Users/robbievanleeuwen/Documents/Programming/section-properties/sectionproperties/pre/library/concrete_sections.py", line 288, in add_reinforcement
    base_geom = base_geom - reinforcement
  File "/Users/robbievanleeuwen/Documents/Programming/section-properties/sectionproperties/pre/geometry.py", line 1057, in __sub__
    raise ValueError(
ValueError: Cannot perform 'difference' on these two objects: <sectionproperties.pre.geometry.CompoundGeometry object at 0x7fa4e52cae50> - <sectionproperties.pre.geometry.Geometry object at 0x7fa4e52caca0>
```

Adding `self.assigned_control_point = None` to the `__init__` of `CompoundGeometry` fixes this, but results in the previous reinforcing bars being deleted and only the rectangular concrete section remaining when `base_geom = base_geom - reinforcement` is run. As a result seems like this method only really works on `Geometry` objects and not `CompoundGeometry` objects. Here is the end result:

Screen Shot 2022-02-23 at 4 29 07 pm

Would it be possible to get the subtract operator to work for `CompoundGeometry`? Or am I doing something wrong here :)

### PR DESCRIPTION
**Pull request by connorferster**
Fix #194

### CODE REVIEW

**Comment by connorferster** [comment]
Note, this fix won't necessarily improve the behaviour of the creation of concrete sections. Will be submitting a separate PR proposing a new approach to concrete sections.

**Comment by robbievanleeuwen** [comment]
@connorferster no longer get the AttributeError on my end, however as you may have realised the `__sub__` method isn't working quite as expected as it seems you can only have two geometries max? (Each successive `__sub__` seems to delete the previous `__sub__`?)

**Comment by robbievanleeuwen** [comment]
Example from #198 (should be 3 bars):
Figure_1

**Comment by connorferster** [comment]
Example in #198 now produces:
image

**Review by robbievanleeuwen — APPROVED** [review]

**Pull request merged**
