### PR TITLE
Add progress bar to time_info

### PR DESCRIPTION
**Pull request by robbievanleeuwen**
Recently came across [progress](https://github.com/verigak/progress), a neat package that gives you a loading bar and time info and thought it looked a fair bit more professional than what is currently implemented for ``time_info=True``.

So here is an implementation of progress in _sectionproperties:_

time_info

Works pretty well! Keen to hear any thoughts/suggestions on this one before I merge!

### CODE REVIEW

**Comment by robbievanleeuwen** [comment]
@Czarified wow this is a really impressive package, don't know how I haven't come across it!

I'll have a look at it in detail and maybe incorporate this instead! Would be nice to also use this for printing results to the terminal!

**Comment by connorferster** [comment]
I have just started using Rich, too. Will McGugan is always being featured/talked about on PythonBytes.fm especially once he quit his job to focus solely on his open source projects! (Rich and Textual). Both very cool.

**Comment by connorferster** [comment]
> @Czarified wow this is a really impressive package, don't know how I haven't come across it!
> 
> I'll have a look at it in detail and maybe incorporate this instead! Would be nice to also use this for printing results to the terminal!

@robbievanleeuwen You obviously have not been listening to PythonBytes! ;) "Python news and headlines directly to your earbuds..."

**Comment by connorferster** [comment]
I wonder what the deal is the with the Python 3.9 test on Mac OS...

**Comment by robbievanleeuwen** [comment]
> I have just started using Rich, too. Will McGugan is always being featured/talked about on PythonBytes.fm especially once he quit his job to focus solely on his open source projects! (Rich and Textual). Both very cool.

Just had a look at Textual, what madness!

**Comment by connorferster** [comment]
Madness!!! Sweet madness! :)))

I pulled the repo this eve and tried running the example 06. The progress bar did not show up for me so will have to check it out further. Had to work on project work late tonight so will try again later.

**Comment by robbievanleeuwen** [comment]
@connorferster I modified example 6 to include time_info=True in the gif, but I don't it's like that by default. Hoping that's the issue?

**Comment by connorferster** [comment]
😂…that’s probably it

**Comment by robbievanleeuwen** [comment]
Update on this with my take on the `Rich` progress bar:

progress

Tested on mac terminal, Windows terminal preview (bold doesn't seem to work?) and Windows anaconda prompt (a bit of flickering?). Haven't looked at Jupyter yet for compatibility.

Open to thoughts/comments.

Will also look to implementing `Rich` for all text printed to the terminal.

**Comment by robbievanleeuwen** [comment]
Minor fix and seems to work well in jupyter:

progress

**Comment by Czarified** [comment]
Absolutely gorgeous! Great job Robbie! I'll pull this down and try it out on Windows Terminal, but I probably won't get to it before the weekend.

**Comment by Czarified** [comment]
It works on Windows, with my Windows Terminal setup, as expected

.

**Pull request merged**
