### PR TITLE
Update steelsections.py to create bulb flat

### PR DESCRIPTION
**Pull request by zmpulse**
Update steelsections.py to create bulb flat

### CODE REVIEW

**Comment by robbievanleeuwen** [comment]
@zmpulse there are some comments in your code which confuse me:

```python
dzero = ((c + t * 0.5 - r - t * 0.5) ** 2 + (b - r - b + d) ** 2) ** 0.5
# build radius
"""
to be update to include small radius on all sharp edge
to be update for tangence of the oblic line :
points.append([(r**2)/(dzero**2)*(t * 0.5)+r/(dzero**2)*((dzero**2)-(r**2))**0.5*(d-b),
              r**2/dzero**2*(b-d)+r/dzero**2*(dzero**2-r**2)**0.5*(t*0.5)])
points.append([(r**2)/(dzero**2)*(t * 0.5)-r/(dzero**2)*((dzero**2)-(r**2))**0.5*(d-b),
              r**2/dzero**2*(b-d)-r/dzero**2*(dzero**2-r**2)**0.5*(t*0.5)])"""
```

Also `dzero` isn't currently being used. Is the implementation complete?

**Comment by robbievanleeuwen** [comment]
@zmpulse could you please clarify how the dimensions work? See below code (I have shifted the section so the bottom left corner is at `(0, 0)`:

```python
from sectionproperties.pre.library.steel_sections import bulb_section

geometry = bulb_section(d=250, d_b=30, b=50, t=12, r=10, n_r=16).shift_section(6)
geometry.plot_geometry()
```

This generates the following figure which I have marked up:

Figure_1

These dimensions do not seem to align with the dimensions I have provided. Further there are some sharp transitions between straight lines and radii which do not look right. Are you able to comment on these?

**Comment by robbievanleeuwen** [comment]
Hi @zmpulse wondering if you are still interested in working on this? If not, I will close this PR.

**Comment by zmpulse** [comment]
Hi Robbie,
I have followed the convention ISO code for bulb flat and vendor.
image
image

So the full width of the bulb is at web thickness and bulb width. So in our case 50mm+12mm=62mm so it is ok.
For the small radius you are rigth on all sharp edge there is a small radius. (mentionned in the comments """to be update to include small radius on all sharp edge""").
For the sharp edge mention on the tangential line I will cross scheck it.

Thanks Robbie

**Comment by zmpulse** [comment]
I have found the width and depth of bulb that you used lead to an angle out of the standard because they don't respect the 30° angle of profile.
image
So if the parameter are not respected this generate sharp edge at tangential line.

**Comment by zmpulse** [comment]
image
done I will implement it now in the code

**Comment by zmpulse** [comment]
it is made:
`if d_b == float:
        d_b = r * np.cos(np.pi / 3) / np.cos(np.pi / 6) + r + c * np.tan(np.pi / 6)  `

**Pull request merged**
