### PR TITLE
Mesh plot fix

### PR DESCRIPTION
**Pull request by connorferster**
To fix appearance of mesh plots in the examples.

### CODE REVIEW

**Comment by Spectre5** [comment]
Some parameters are not documented in the plot_mesh function (not from this PR).  Otherwise, in the examples I don't think you have really changed things here as the defaults with these calculations using size are the same, or similar, to what they were before.  I think?  I still don't see the mesh in the readthedocs files.

I think for the plotting it is probably best to pass things via kwargs to the matplotlib functions too (I think I did this to some extent in that old PR too, if I recall correctly, if you want to see how I approached that).

**Comment by connorferster** [comment]
Yeah, the updated plots won't show up on the v2 RTD site yet. I ran the build locally and observed the updated mesh plots. You can see that the examples on the v2 site are still running old code that references `sectionproperties.analysis.cross_section` which has now been updated to `sectionproperties.analysis.section`, etc.

**Comment by robbievanleeuwen** [comment]
New build still has the same [issues](https://sectionproperties--158.org.readthedocs.build/en/158/sphinx_gallery_examples/index.html#basic-examples). I also get the desired behaviour locally. I'm optimistically doing some digging in the sphinx-gallery docs 🤞

**Comment by Spectre5** [comment]
Did you try a bigger figure yet?  Thicker lines?  And no transparency?

**Comment by Spectre5** [comment]
Also it sounds like it works fine locally for both of you?  And one of you are on Windows and other on Linux?  If so then I'd probably guess a reathedocs issue, so maybe there is something worth changing there?  I know projects do you sphinx gallery with readthedocs.  Maybe find one with busy charts and see if they do anything unique.  I know pyvista used to, but they now use GitHub pages last I looked.

**Comment by connorferster** [comment]
@robbievanleeuwen On RTD, are the docs getting built with the newest code? i.e. the imports on the examples are showing pre.library.standard_sections, etc?

**Comment by connorferster** [comment]
> Also it sounds like it works fine locally for both of you? And one of you are on Windows and other on Linux? If so then I'd probably guess a reathedocs issue, so maybe there is something worth changing there? I know projects do you sphinx gallery with readthedocs. Maybe find one with busy charts and see if they do anything unique. I know pyvista used to, but they now use GitHub pages last I looked.

Yeah, it builds fine and looks good for me on Windows. I think its a readthedocs issue. I am guessing that it's not updating the code in the v2 build. I suggest this because I noticed that the v2 build docs are at least a couple of commit/merges behind.

**Comment by robbievanleeuwen** [comment]
> Did you try a bigger figure yet? Thicker lines? And no transparency?

Will try a few of these things, my feeling is that it has something to do with triplot running on the readthedocs server because all the other plot types are fine?



> @robbievanleeuwen On RTD, are the docs getting built with the newest code? i.e. the imports on the examples are showing pre.library.standard_sections, etc?

Readthedocs is building the code in this pull request, see the link at the bottom of the checks or [here](https://sectionproperties--158.org.readthedocs.build/en/158/) so don't think this is an issue.

**Comment by robbievanleeuwen** [comment]
@connorferster the v2 docs are currently failing because they don't have the commit b97a579 in this PR yet so still look old.

**Comment by connorferster** [comment]
@robbievanleeuwen Yes, thanks for catching those! However, I did update the Examples with the new imports one or two merges ago so the Examples should be showing the new imports but they do not. This leads me to think readthedocs is not "reloading" the new code or something like that.

**Comment by connorferster** [comment]
@Spectre5 Thanks for posting that link to the new build. I see the mesh fine on the Examples now. Problem solved?

**Comment by robbievanleeuwen** [comment]
@connorferster yes it's there now but still so light, still barely noticeable for my terrible eyes. I'm going to see if I can get it any darker.

**Comment by connorferster** [comment]
@robbievanleeuwen Ah, I see that the stress contour plots are plotting the contours but not mesh any more.

In terms of the line-weight, feel free to adjust. I scaled it to 0.1*size/dpi and 0.3 alpha because on the small graphics I found the lines getting really dark/crowded on the finer meshes. Please set them to a value that you think looks best.

**Comment by robbievanleeuwen** [comment]
@connorferster yep I'll have a play with these. Still puzzling that the `plot_geometry()` and the contour portions of the stress plots look exactly the same to me on rtd & locally, just the `plot_mesh()` and mesh in the stress plots is so different!?!?!

**Comment by robbievanleeuwen** [comment]
Well found the culprit... New matplotlib 3.5.1 seems to have some big changes to the way the plots look. Funnily enough I couldn't figure out what exactly the change is in the release notes? Pinning matplotlib to 3.4.2 fixes the plots, but have created #159 to discuss supporting 3.5.x.

See docs [here](https://sectionproperties.readthedocs.io/en/mesh_plot_fix/sphinx_gallery_examples/index.html#basic-examples) (couldn't get PR docs to refresh).

**Review by robbievanleeuwen — APPROVED** [review]

**Pull request merged**
