### PR TITLE
Loosen warping reqs for stress analysis

### PR DESCRIPTION
**Pull request by robbievanleeuwen**
Only require a warping analysis to be performed for a stress analysis if the shear force or twisting moment is non-zero.

### CODE REVIEW

**Comment by robbievanleeuwen** [comment]
@connorferster wondering if you've had a chance to look at this and whether or not it's fit for purpose for your use case?

**Review by connorferster — APPROVED** [review]
Looks good to me! Are you up for adding a test for triggering the `RuntimeError`s?

**Comment by connorferster** [comment]
Woo woo! We are up over 59.5% for code coverage! 60%, here we come! :)

**Comment by robbievanleeuwen** [comment]
😆 setting myself the goal of improving the test coverage over the coming weeks, we'll see how we go!

Thinking about doing a bit of a refactor as well as switching the docs from RTD over to GH pages, similar to *concreteproperties*. Will break a few links in the github repo which I'll try to patch but I think it will be an overall improvement.

**Pull request merged**
