### PR TITLE
Fix shapely imports; fix test_filter_non_polygons

### LINKED ISSUE #258: Some shapely imports need to be fixed for compatibility with shapely v2.0
**Describe the bug**
Shapely 2.0 has been released (!!!) Yay!

However it seems that this kind of import:

```python
import shapely

shapely.affinity.translate(geom, ...)
```
Needs to be replaced with this:

```python
from shapely import affinity

affinity.translate(geom, ...)
```

**To Reproduce**
Steps to reproduce the behaviour:
Run test suite with shapely 2.0 installed

**Additional context**
Have not checked this out extensively. Need to see what the extent is...

### PR DESCRIPTION
**Pull request by robbievanleeuwen**
Fix errors resulting from shapely version 2, closes #258 

@normanrichardson it looks like the STRtree implementation has changed, see [here](https://shapely.readthedocs.io/en/latest/release/2.x.html#strtree-api-changes-and-improvements). After a quick look I couldn't exactly figure out how ours is working. If you have time, would you be able to have a quick look at fixing this by creating a PR to this branch? If not I can dig a bit deeper in the new year and try to figure it out 😄

### CODE REVIEW

**Comment by normanrichardson** [comment]
Hi @robbievanleeuwen, I'll be happy to help get that fixed

**Comment by robbievanleeuwen** [comment]
Thanks @normanrichardson, appreciated!

**Comment by normanrichardson** [comment]
Hi @robbievanleeuwen, I think #261 handles the changes to STRtree. Let me know if I've missed anything

**Comment by robbievanleeuwen** [comment]
Thanks @normanrichardson!

@connorferster this is ready, let me know if you've got time for a quick review :)

**Review by connorferster — APPROVED** [review]

**Comment by connorferster** [comment]
Looks good to me! I like how the shapely API has been simplified to offer the most common objects and functions in the top-level namespace.

**Pull request merged**
